config/routes.rb
Rails.application.routes.draw do
  resources :stats, only: [:index] do
    get :weekly
    get :monthly
    collection do
      get :group_score_card
    end
  end

  get "login", to: "login#create"
  get "login/callback", to: "login#callback"
  get "auth/oktaoauth/callback", to: "login#callback"
  get "login/clear", to: "login#clear"
  get "login/error", to: "login#error"

  root to: redirect("/stats")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def create
    authorize_params = OktaOauth.authorize_params(prompt: params[:prompt]&.to_s)
    session[:oauth_state] = authorize_params.state
    redirect_to authorize_params.redirect_url, allow_other_host: true
  end

  def error
  end

  def callback
    if error_response? || !session_match_state?
      redirect_to(login_error_path)
      return
    end

    setup_session
    redirect_to stats_url
  end

  def clear
    session.clear
    render plain: "OK"
  end

  private

  def error_response?
    return unless params[:error]

    Rollbar.error(params[:error], error_description: params[:error_description])
    true
  end

  def session_match_state?
    params[:state] == session[:oauth_state]
  end

  def setup_session
    okta_token = OktaOauth.exchange_code(params[:code].to_s)
    session[:okta_access_token] = okta_token.access_token
    session[:okta_expires_at] = okta_token.expires_at.to_i
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_action :ensure_mpdx_active, :target_date

  def index
    @user_account_lists = loader.load_user_ccount_lists
    @coaching_account_lists = loader.load_coaching_ccount_lists
  end

  def weekly
    @account_list = loader.load_account_list
    @data = loader.load_stats(:weekly)
    @table = AccountListStatsTable.new(@data).table(:weekly)
    render :show
  end

  def monthly
    @account_list = loader.load_account_list
    @data = loader.load_stats(:monthly, @target_date)
    @table = AccountListStatsTable.new(@data).table(:monthly)
    render :show
  end

  def group_score_card
    @data = {}
    params[:stat_ids] = JSON.parse(params[:stat_ids]) if params[:stat_ids].instance_of?(String)
    goal = params[:goal].to_i

    params[:stat_ids].each do |stat_id|
      params[:stat_id] = stat_id
      name = loader.load_account_list["attributes"]["name"]
      @data[name] = loader.load_stats(:group, @target_date)
    end
    @table = AccountListGroupStatsTable.new(@data).table(:group, goal)
  end


  private

  def loader
    @loader = AccountListStatsLoader.new(account_list_id: params[:stat_id],
                                           token: session[:mpdx_token],
                                           env: params[:env])
  end

  def target_date
    @target_date = params[:target_date]&.to_date || Date.today
  end

  def ensure_mpdx_active
    return if session[:mpdx_expires_at].to_i > DateTime.now.to_i
    if session[:okta_expires_at].to_i < 30.seconds.from_now.to_i
      redirect_to login_url
      return false
    end
    token = MPDXLogin.login(session[:okta_access_token])
    session[:mpdx_token] = token.token
    session[:mpdx_expires_at] = token.expires_at.to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmfReport</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- load MUI -->
    <link href="//cdn.muicss.com/mui-0.10.3/css/mui.min.css" rel="stylesheet" type="text/css" />
    <script src="//cdn.muicss.com/mui-0.10.3/js/mui.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="mui-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/login/error.html.erb
<h1>Login Error</h1>
<p><%= link_to "Try Again", login_path, class: "btn btn--green" %></p>

app/views/stats/group_score_card.html.erb
<h2 class="m-bottom-0">Level of Effort Report for Group</h2>

<p><%= link_to 'View a Different Account', stats_path(env: params[:env]) %></p>

<%= form_with url: group_score_card_stats_path, method: :get do |form| %>
 <div class="form-inputs">
    <%= form.label :target_date, "Select Month:" %>
    <%= form.select :target_date, (0..11).map{ |i| "#{Date::MONTHNAMES[(Date.today - i.month).month]} #{(Date.today-i.month).year}" }, { selected: params[:target_date] } %>
    <%= form.hidden_field :stat_ids, value: "#{params[:stat_ids]}" %>
    <%= form.hidden_field :goal, value: "#{params[:goal]}" %>
    <%= form.hidden_field :env, value: params[:env] %>
    <%= form.submit "View Report" %>
  </div>
<% end %>

<table>
  <% @table.each do |row| %>
  <tr>
    <% row[:cells].each do |cell| %>
    <% if row[:type] == 'header' %>
    <th colspan="<%= cell[:colspan] %>" class="<%= cell[:class] %>"><%= cell[:text] %></th>
    <% else %>
    <td colspan="<%= cell[:colspan] %>" class="<%= cell[:class] %>"><%= cell[:text] %></td>
    <% end %>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/stats/index.html.erb
<h1>Choose a Report</h1>

<h2>Your Accounts:</h2>
<ul>
  <% @user_account_lists.each do |account_list| %>
    <li><%= link_to account_list['attributes']['name'], stat_weekly_path(account_list['id'], env: params[:env]) %></li>
  <% end %>
</ul>

<h2>People You Coach:</h2>
<ul>
  <% @coaching_account_lists.each do |account_list| %>
    <li><%= link_to account_list['attributes']['name'], stat_weekly_path(account_list['id'], env: params[:env]) %></li>
  <% end %>
</ul>

<h2>Group Report:</h2>
<i>Select the accounts to include in your group report.</i>

<%= form_with url: group_score_card_stats_path, method: :get do |form| %>
  <div class="form-inputs">
      <% (@user_account_lists + @coaching_account_lists).each do |account_list| %>
        <%= form.check_box :stat_ids, {multiple: true}, account_list['id'], nil %>
        <%= form.label :stat_ids, "#{account_list['attributes']['name']}" %><br>
    <% end %>
    <%= form.label :goal, "Group Goal:" %>
    <%= form.number_field :goal, in: 0..100000, step: 1, value: 0 %><br>
    <%= form.hidden_field :env, value: params[:env] %><br>
  <%= form.submit "View Report" %>
  </div>
<% end %>

app/views/stats/show.html.erb
<h2 class="m-bottom-0">Level of Effort Report for</h2>
<h1 class="m-top-0"><%= @account_list['attributes']['name'] %></h1>
<p><%= link_to 'View a Different Account', stats_path(env: params[:env]) %></p>
<p>
  <%= link_to 'Weekly', stat_weekly_path(params[:stat_id], env: params[:env]) %> -
  <%= link_to 'Monthly', stat_monthly_path(params[:stat_id], env: params[:env]) %>

  <% if params[:action] == "monthly" %>
    <%= form_with url: stat_monthly_path, method: :get do |form| %>
      <div class="form-inputs">
        <%= form.label :target_date, "Select Month:" %>
        <%= form.select :target_date, (0..11).map{ |i| "#{Date::MONTHNAMES[(Date.today - i.month).month]} #{(Date.today-i.month).year}" }, { selected: params[:target_date] } %>
        <%= form.hidden_field :stat_id, value: "#{params[:stat_ids]}" %>
        <%= form.hidden_field :env, value: params[:env] %>
        <%= form.submit "View Report" %>
      </div>
    <% end %>
  <% end %>
</p>

<table>
  <% @table.each do |row| %>
  <tr>
    <% row[:cells].each do |cell| %>
    <% if row[:type] == 'header' %>
    <th colspan="<%= cell[:colspan] %>" class="<%= cell[:class] %>"><%= cell[:text] %></th>
    <% else %>
    <td colspan="<%= cell[:colspan] %>" class="<%= cell[:class] %>"><%= cell[:text] %></td>
    <% end %>
    <% end %>
  </tr>
  <% end %>
</table>